### ISSUE TITLE
Safety of Using consecutively uint64 for ServiceNodeID in Concurrent Operations?

### ISSUE THREAD

**Issue by venezuela01** [oxen-io/eth-sn-contracts#8]
```
    uint64 public nextServiceNodeID = 1;
```

```
    /// @notice Liquidates a BLS public key using a signature. This function can be called by anyone if the network wishes for the node to be removed (ie from a dereg) without relying on the user to remove themselves
    /// @param serviceNodeID The ID of the service node to be liquidated.
    /// @param sigs0 First part of the signature.
    /// @param sigs1 Second part of the signature.
    /// @param sigs2 Third part of the signature.
    /// @param sigs3 Fourth part of the signature.
    /// @param ids An array of service node IDs.
    function liquidateBLSPublicKeyWithSignature(uint64 serviceNodeID, uint256 sigs0, uint256 sigs1, uint256 sigs2, uint256 sigs3, uint64[] memory ids) external {
```

Is it safe to use consecutively uint64 for ServiceNodeID rather than UUID/hash?

Are there any risks of potential race conditions and ID collisions?

Consider a scenario where the network agrees to liquidate node_1 and node_100, and two calls to `liquidateBLSPublicKeyWithSignature()` are submitted almost simultaneously. Is it possible for these two calls to be mined in the same EVM block, where the first call successfully deletes node_1 but also subtly updates the rest of the indices? As a result, the actual node_100 deleted by the second call might be the previously non-guilty node_101, rather than the guilty one.

In another scenario, suppose the network agrees to liquidate node_1. Could an attacker modify the non-signer set, construct a parallel `liquidateBLSPublicKeyWithSignature()` call with a replay attack but slightly different parameters, attempting to delete node_1 again? However, since the guilty node_1 has already been deleted, could a new non-guilty node_1, previously node_2, get deleted?

**Comment by darcys22** [comment]
The evm handles the first point natively.

https://ethereum.stackexchange.com/questions/69334/how-do-smart-contracts-handle-race-conditions#69335

In your second point “modifying the non-signer set”, if you mean modifying the array passed in as a param to the liquidate function then the signature is invalidated because it rebuilds the signed message using those params. If you mean that the service node linked list has changed after the node is deleted then either the signature is invalidated (if they previously signed and are no longer allowed to sign) otherwise the check in the remove bls key function catches it and throws an error saying node does not exist.

It sounds like there is some misunderstanding about how the identifiers are used. Nodes dont change their ids when adding or removing from the list, so deleting node id 1 wont mean that node 2 id will be decremented.
